export { default as Table } from './Table.vue'
export { default as TableHeader } from './TableHeader.vue'
export { default as TableHeaderColumn } from './TableHeaderColumn.vue'
export { default as TableRow } from './TableRow.vue'
export { default as TableColumn } from './TableColumn.vue'
export { default as TableColumnPicture } from './TableColumnPicture.vue'
